### ISSUE TITLE
Wrong canonicalWebUrl written by centos image

### ISSUE THREAD

**Issue by reda-alaoui** [GerritCodeReview/docker-gerrit#2]
I am using `gerritcodereview/gerrit:2.15.rc2`.

I want to run the gerrit container and access it via apache httpd reverse proxy. So before starting the container I setup `canonicalWebUrl` in `gerrit.config`.

But on each container boot, `canonicalWebUrl` is overwritten because of https://github.com/GerritCodeReview/docker-gerrit/blob/master/centos/7/Dockerfile#L25.

This is problematic because login page tries to redirect me to the `canonicalWebUrl`.
Except that, the application works fine.

Am I doing something wrong?

`docker-compose.yaml`:
```yaml
version: '3.4'

services:
  gerrit:
    image: gerritcodereview/gerrit:2.15.rc2
    ports:
      - "29418:29418"
      - "12080:8080"
    links:
      - gerrit-postgres
    depends_on:
      - gerrit-postgres
    volumes:
     - /data/gerrit/git:/var/gerrit/git
     - /data/gerrit/index:/var/gerrit/index
     - /data/gerrit/cache:/var/gerrit/cache
     - /etc/gerrit:/var/gerrit/etc
    #entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit

  gerrit-postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=*****
      - POSTGRES_PASSWORD=******
      - POSTGRES_DB=gerrit
    volumes:
      - /data/gerrit/postgres:/var/lib/postgresql/data
```

`gerrit.config` after container startup:
```
[gerrit]
  basePath = git
  ui = POLYGERRIT
        canonicalWebUrl = http://a374b4c19a09:8080/
        serverId = c8d2bd74-84ed-4921-bc24-b8639097cee9

[database]
  type = postgresql
  hostname = gerrit-postgres
  database = *****
  username = ******
  password = ******

[index]
  type = LUCENE

[auth]
  type = ldap
  gitBasicAuth = true
        gitBasicAuthPolicy = HTTP

[ldap]
  server = ****
  sslVerify = false
  username = ****
  password = ****
  accountBase = ****
  accountPattern = *****
  accountFullName = displayName
  accountEmailAddress = mail

  groupBase = ****

[sendemail]
  smtpServer = localhost

[sshd]
  listenAddress = *:29418

[httpd]
  listenUrl = http://*:8080/

[cache]
  directory = cache
```
